###
- hosts: all
  become: true
    # Variable Initialization
  vars:
    APP_MESSAGE: "Testing for Rebuild of Docker Image"
  
  tasks:
    # Docker Installation
    - name: install docker
      yum:
        name: docker
        state: latest

    # Create services and start Docker
    - name: copy myapp service
      ansible.builtin.copy:
        src: ./myapp.service
        dest: /etc/systemd/system/myapp.service
        owner: root
        mode: '0644'
    
    #Enable myapp in Systemd
    - name: enable myapp service
      ansible.builtin.systemd:
        name: myapp
        enabled: yes
        daemon_reload: yes

    #Start Docker
    - name: start docker
      ansible.builtin.systemd:
        name: docker
        state: started

    # Wait Function
    - name: wait for docker prompt
      ansible.builtin.debug:
        msg: "Waiting for docker to start"

    #Double Checking for Docker to be started? :D :D :D
    - name: wait for docker
      service:
        name: docker
        state: started
      become: yes

    # Copy App
    - name: copy app
      ansible.builtin.copy:
        src: ./app
        dest: /tmp/build_app

    # App Variables
    - name: update app message
      replace:
        path: /tmp/build_app/app/main.py
        backup: yes
        regexp: "APP_MESSAGE"
        replace: "{{ APP_MESSAGE }}"
    
    # Build App
    - name: build app
      command: docker build -t myapp /tmp/build_app/app

  # Start App
    - name: start myapp
      service:
        name: myapp
        state: started
